name: ditto
description: oh say it ditto

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.14.0
  tiledjsonreader: ^1.3.4
  http: ^1.1.0
  a_star_algorithm: ^0.3.1

  bonfire: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/player/
    - assets/images/enemy/
    - assets/images/npc/
    - assets/images/tile/
    - assets/images/tile_random/
    - assets/images/tiled/
    - assets/images/tiled/top_down/
    - assets/images/tiled/tileset/
    - assets/images/itens/
    - assets/images/lpc/body/
    - assets/images/lpc/feet/
    - assets/images/lpc/hair/
    - assets/images/lpc/leg/
    - assets/images/lpc/torco/
    - assets/images/lpc/head/
    - assets/images/lpc/gloves/